// GeneratorTemplate.swift
// SwiftCodeGen
//
// Template for creating new code generators

import Foundation

// MARK: - Generator Protocol

/// Protocol for code generators.
public protocol Generator {
    /// The name used in CLI and configuration.
    var name: String { get }
    
    /// Description shown in help text.
    var description: String { get }
    
    /// Generates code based on configuration.
    func generate(config: GeneratorConfig) throws -> [GeneratedFile]
}

// MARK: - Configuration

/// Configuration for a generator.
public struct GeneratorConfig {
    /// Input file or directory paths.
    public let inputPaths: [String]
    
    /// Output directory path.
    public let outputPath: String
    
    /// Additional options.
    public let options: [String: Any]
    
    public init(
        inputPaths: [String],
        outputPath: String,
        options: [String: Any] = [:]
    ) {
        self.inputPaths = inputPaths
        self.outputPath = outputPath
        self.options = options
    }
}

// MARK: - Generated File

/// Represents a generated source file.
public struct GeneratedFile {
    /// The file name (e.g., "Mocks.swift").
    public let name: String
    
    /// The file content.
    public let content: String
    
    /// The relative path within output directory.
    public let path: String?
    
    public init(name: String, content: String, path: String? = nil) {
        self.name = name
        self.content = content
        self.path = path
    }
}

// MARK: - Template Generator

/// A template generator demonstrating best practices.
public struct TemplateGenerator: Generator {
    public let name = "template"
    public let description = "Template generator example"
    
    // MARK: - Initialization
    
    public init() {}
    
    // MARK: - Generation
    
    public func generate(config: GeneratorConfig) throws -> [GeneratedFile] {
        var files: [GeneratedFile] = []
        
        for inputPath in config.inputPaths {
            let sourceContent = try String(contentsOfFile: inputPath)
            let parsed = try parse(sourceContent)
            let generated = try generateCode(from: parsed, config: config)
            
            files.append(GeneratedFile(
                name: "\(parsed.name)Generated.swift",
                content: generated
            ))
        }
        
        return files
    }
    
    // MARK: - Parsing
    
    private struct ParsedInput {
        let name: String
        let declarations: [Declaration]
    }
    
    private struct Declaration {
        let name: String
        let type: String
        let parameters: [Parameter]
    }
    
    private struct Parameter {
        let name: String
        let type: String
    }
    
    private func parse(_ content: String) throws -> ParsedInput {
        // Parse the input source code
        // This is a simplified example
        
        return ParsedInput(
            name: "Example",
            declarations: [
                Declaration(
                    name: "doSomething",
                    type: "Void",
                    parameters: [
                        Parameter(name: "value", type: "Int")
                    ]
                )
            ]
        )
    }
    
    // MARK: - Code Generation
    
    private func generateCode(
        from parsed: ParsedInput,
        config: GeneratorConfig
    ) throws -> String {
        var output = """
        // Generated by SwiftCodeGen
        // DO NOT EDIT
        
        import Foundation
        
        """
        
        output += generateClass(from: parsed)
        
        return output
    }
    
    private func generateClass(from parsed: ParsedInput) -> String {
        var code = """
        /// Generated \(parsed.name)
        public final class \(parsed.name)Generated {
        
        """
        
        for decl in parsed.declarations {
            code += generateMethod(from: decl)
        }
        
        code += "}\n"
        return code
    }
    
    private func generateMethod(from decl: Declaration) -> String {
        let params = decl.parameters.map { "\($0.name): \($0.type)" }.joined(separator: ", ")
        
        return """
            /// Generated method
            public func \(decl.name)(\(params)) -> \(decl.type) {
                // Generated implementation
            }
        
        """
    }
}

// MARK: - Mock Generator Example

/// Example mock generator implementation.
public struct MockGenerator: Generator {
    public let name = "mock"
    public let description = "Generates mock implementations of protocols"
    
    public init() {}
    
    public func generate(config: GeneratorConfig) throws -> [GeneratedFile] {
        // Implementation would:
        // 1. Parse protocol definitions
        // 2. Generate mock classes with:
        //    - Call counting
        //    - Argument capturing
        //    - Return value configuration
        //    - Error throwing support
        
        let content = """
        // Generated by SwiftCodeGen
        // DO NOT EDIT
        
        import Foundation
        
        /// Mock error for unconfigured calls.
        enum MockError: Error {
            case notConfigured
        }
        
        // Protocol mocks would be generated here...
        """
        
        return [GeneratedFile(name: "Mocks.swift", content: content)]
    }
}

// MARK: - Code Builder

/// Helper for building generated code.
public struct CodeBuilder {
    private var lines: [String] = []
    private var indentLevel = 0
    
    public init() {}
    
    public mutating func addLine(_ line: String = "") {
        let indent = String(repeating: "    ", count: indentLevel)
        lines.append(indent + line)
    }
    
    public mutating func indent() {
        indentLevel += 1
    }
    
    public mutating func dedent() {
        indentLevel = max(0, indentLevel - 1)
    }
    
    public mutating func addBlock(
        _ header: String,
        _ build: (inout CodeBuilder) -> Void
    ) {
        addLine(header + " {")
        indent()
        build(&self)
        dedent()
        addLine("}")
    }
    
    public func build() -> String {
        lines.joined(separator: "\n")
    }
}

// MARK: - Usage Example

/*
let generator = TemplateGenerator()
let config = GeneratorConfig(
    inputPaths: ["./Sources/Protocols"],
    outputPath: "./Generated"
)

let files = try generator.generate(config: config)
for file in files {
    try file.content.write(
        toFile: "\(config.outputPath)/\(file.name)",
        atomically: true,
        encoding: .utf8
    )
}
*/
